### ISSUE TITLE
E-MAIL Addon 1.6.8c: Header no more compliant with rules from WEB.DE

### ISSUE THREAD

**Issue by adb336** [jens-maus/hm_email#14] opened 2020-05-18 07:54 UTC
Dear all,

since a week I am getting back from WEB.DE the following message when I try to send mail from CCU3, actual release 3.51.6:

May 18 09:39:54 host=smtp.web.de tls=on auth=on user=XXXXXX from=XXXXXX@web.de recipients=me@TLD,other@TLD smtpstatus=554 smtpmsg='554-Transaction failed\n554-Reject due to policy restrictions.\n554 For explanation visit https://postmaster.web.de/error-messages?ip=87.158.232.147&c=hi' errormsg='the server did not accept the mail' exitcode=EX_UNAVAILABLE

Please advise.

Kind regards,

Alexander De Bernardi

**Comment by jens-maus** [comment] 2020-05-18 08:06
Duplicate of #13

**Closed by jens-maus** 2020-05-18 08:06 UTC

**Comment by adb336** [comment] 2020-06-01 09:50
Solution for #13 works also for web.de.
